import Head from 'next/head'
import Image from 'next/image'
import BottomNavBar from '../../components/BottonNavBar'
import {useRouter} from 'next/router'
import { useState, useEffect} from 'react'
import Header from '../../components/Header'
import PuffLoader from "react-spinners/PuffLoader";
import { css } from "@emotion/react";
import { PaperAirplaneIcon, PaperClipIcon, PhotographIcon } from '@heroicons/react/outline'
function Activity() {
    const [loading, setLoading] = useState(true)
    let [color, setColor] = useState("#16a085");
    useEffect(() =>{
        setInterval(() => {
            setLoading(false)
        }, 3000)
    })
    const override = css`
        display: block;
        margin: 0 auto;
        border-color: #16a085;
        `;
    if(loading) {
        return (
            <div className="flex flex-col h-screen w-full items-center justify-center">
                <p className="text-3xl text-green-500">Greenupp Feeds</p>
                <p className="text-center mb-10 text-gray-500">Precise information</p>
                <PuffLoader color={color} loading={loading} css={override} size={60} />
            </div>
        )
    }
    return (
        <div className="main">
            <Head>
                <title>Greenupp | Activity and Feeds</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="flex space-y-3 flex-col justify-start items-left h-screen pt-20 px-4">
                <p className="text-3xl">Feed</p>
                <div className="bg-gray-100 h-auto w-full rounded-2xl p-2 space-y-2">
                    <p className="">Share your thoughts</p>
                    <div className="bg-white rounded-2xl">
                        <form className="">
                            <textarea type="text" className="w-full outline-none bg-transparent p-2 " placeholder=""></textarea>
                        </form>
                        
                    </div>
                    <div className="flex">
                        <div className="flex space-x-2 w-full p-2">
                            <button className=""><PhotographIcon className="h-6 w-6 text-green-600"/></button>
                            <button className=""><PaperClipIcon className="h-6 w-6 text-green-600"/></button>
                        </div>
                        <div className="flex space-x-2 p-2">
                            <button className="bg-green-600 px-6 py-3 rounded-2xl text-white">Post</button>
                        </div>
                    </div>
                    
                </div>
            </section>
            <nav className="">
                <BottomNavBar />
            </nav> 
        </div>
    )
}

export default Activity
