import Head from 'next/head'
import Image from 'next/image'
import BottomNavBar from '../../components/BottonNavBar'
import {useRouter} from 'next/router'
import Header from '../../components/Header'
import { ArrowCircleRightIcon, ArrowLeftIcon, ChevronDownIcon, ChevronRightIcon, ChipIcon, InformationCircleIcon, MinusIcon, PlusIcon, SearchIcon, ShieldCheckIcon, ShoppingCartIcon, TrashIcon } from '@heroicons/react/outline'
function Product() {
    const router = useRouter()
    return (
        <div className="main">
            <Head>
                <title>Greenupp | Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="flex flex-col py-4 mt-16 px-2 space-y-2">
               <div className="flex border-b pb-2">
                    <p className="font-bold text-xl">Your Cart</p>
               </div>
               <p>4 Items</p>
               <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/pineapples.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Pineapples </p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 28.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-400 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>
                <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/apples.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Mediterranean Red Apples</p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 15.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-600 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>
                <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/cabbage.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Cabbage</p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 28.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-400 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>
                <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/spinach.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Spinach </p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 28.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-400 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>
                <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/spinach.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Spinach </p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 28.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-400 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>
                <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/spinach.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Spinach </p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 28.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-400 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>
                <div className="flex space-x-2 p-2 rounded-2xl items-center border shadow-sm">
                    <div className="relative h-20 w-20 border p-2 rounded-2xl">
                        <Image src="/spinach.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                    </div>
                    <div className="flex justify-center flex-col">
                        <p className="font-bold text-xl">Spinach </p>
                        {/* <span className="text-sm bg-green-600 w-16 text-center text-white p-1 rounded-full">7 days</span> */}
                        <p className="font-bold text-sm text-gray-400">ZMW 28.54</p>
                        
                    </div>
                    <div className="flex flex-col space-y-2 flex-grow items-end">
                        <button className="">
                            <TrashIcon className="h-6 w-6 bg-gray-400 p-1 text-white rounded-full" />
                        </button>
                        <div className="flex items-center rounded-full w-28 justify-between border border-gray-400 p-2 px-2 space-x-2">
                            <button><PlusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                              <p className="text-gray-600 text-xl">2</p>
                            <button><MinusIcon className="h-6 w-6 p-1 text-white rounded-full bg-gray-400"/></button>
                       </div>
                    </div>
                </div>

            </section>
            <section className="flex bg-white items-center justify-between fixed w-full bottom-0 px-4 p-2 border">
                <div className="flex flex-col w-1/2 border-r space-y-1">
                    <p className="text-sm">Discount <span className="text-md font-bold">ZMW 12.0</span></p>
                    <p className="text-sm">Tax <span className="text-md font-bold">ZMW 5.0</span></p>
                    <p className="text-sm">Total <span className="text-md font-bold">ZMW 101.66</span></p>
                </div>
                <div className="">
                    <button className="uppercase bg-green-600 p-4 rounded-full text-white">Checkout</button>
                </div>
            </section>
            {/* Categories */}
           
        </div>
    )
}

export default Product
