import Head from 'next/head'
import Image from 'next/image'
import BottomNavBar from '../../components/BottonNavBar'
import {useRouter} from 'next/router'
import Header from '../../components/Header'
import { ArrowCircleRightIcon, ChevronRightIcon, PlusIcon, SearchIcon, ShoppingCartIcon } from '@heroicons/react/outline'
import { StarIcon} from '@heroicons/react/solid'
function Store() {
    const router = useRouter()
    return (
        <div className="main">
            <Head>
                <title>Greenupp | Store</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="flex flex-col p-2">
                {/* <div className="flex flex-col justify-center">
                    <p className="text-3xl text-gray-500">Greenupp Store</p>
                    <p className="text-center">Buy  Sell  Rent</p>
                </div> */}
                {/* Tabs */}
                <div className="flex justify-between space-x-2 h-auto mt-16 items-center p-1 py-1 w-full">
                    <button className="bg-green-600 shadow-md text-white p-2 w-full rounded-full h-10">
                        Buy
                    </button>
                    <button className="bg-gray-600 shadow-md text-white p-2 w-full rounded-full h-10">
                        Sell
                    </button>
                    <button className="bg-gray-600 shadow-md text-white p-2 w-full rounded-full h-10">
                        Rent
                    </button>
                </div>
                <div className="w-full py-3 border-b border-gray-300">
                    <form className="flex justify-between border border-gray-500 rounded-full py-1">
                        <input className="outline-none bg-transparent px-4 w-full" type="search" placeholder="Search Store"/>
                        <button className="flex justify-center text-gray-600 p-2 w-16 rounded-full h-10">
                            <SearchIcon className="h-6 w-6"/>
                        </button>
                    </form>
                </div>
                <div onClick={()=>setToggleNotifications(false)} className="flex flex-col fixed bottom-20 right-2 transition duration-200 shadow-xl float-right  items-center justify-center h-16 w-16 rounded-full bg-green-600 z-20">
                    <span className="text-xs bg-white h-4 w-4 font-bold flex items-center justify-center rounded-full">4</span>
                    <ShoppingCartIcon className="h-6 w-6 text-white"/>
                    {/* <span className="text-sm">K400</span> */}
                </div>
            </section>
            {/* Categories */}
            <section className="px-2">
                <h1 className="text-gray-600 text-2xl font-bold">Categories</h1>
                <div className="flex py-2 overflow-auto space-x-1 scrollbar-none">
                    <span className="border border-gray-500  p-2 rounded-full">Vegetables</span>
                    <span className="border border-gray-500 bg-gray-500 text-white p-2 rounded-full">Fruits</span>
                    <span className="border border-gray-500 p-2 rounded-full">Dairy</span>
                    <span className="border border-gray-500 p-2 rounded-full">Legumes</span>
                    <span className="border border-gray-500 p-2 rounded-full">Poultry</span>
                    <span className="border border-gray-500 p-2 rounded-full">Fish</span>
                    <span className="border border-gray-500 p-2 rounded-full">Honey</span>
                </div>
            </section>
            {/* Products */}
            <section className="p-2 pb-20">
                <div className="grid grid-cols-2 gap-2">
                    <div className="flex flex-col p-1 border rounded-2xl shadow-md space-y-2">
                        {/* header */}
                        <div className="py-2 flex justify-between items-center">
                            <p className="font-bold bg-green-600 text-white p-1 px-2 rounded-full">Fresh</p>
                            <ArrowCircleRightIcon onClick={() => {
                                router.push('store/1')
                            }} className="h-8 w-8 text-gray-600"/>
                        </div>
                        <div className="relative h-32 w-full">
                            <Image src="/apples.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                        </div>
                        <div className="px-2">
                            <p className="font-bold">K16.55 <span className="text-gray-400">|</span> Kg</p>
                            <div className="flex justify-between w-full">
                                <p className="font-bold text-gray-600">Mediterranean Red Apples</p>
                                <div className="flex justify-end w-full">
                                    <PlusIcon className="h-8 w-8 text-white bg-green-600 p-1 rounded-full"/>
                                </div>
                            </div>
                            {/* <p className="text-gray-600">6 miles away</p> */}
                        </div>
                        <div className="px-2">
                            <p className="font-bold">Reviews</p>
                            <div className="flex">
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-gray-400"/>
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col p-1 border rounded-2xl shadow-md space-y-2">
                        {/* header */}
                        <div className="py-2 flex justify-between items-center">
                            <p className="font-bold bg-green-600 text-white p-1 px-2 rounded-full">Fresh</p>
                            <ArrowCircleRightIcon className="h-8 w-8 text-gray-600"/>
                        </div>
                        <div className="relative h-32 w-full">
                            <Image src="/banana.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                        </div>
                        <div className="px-2">
                            <p className="font-bold">K9.99 <span className="text-gray-400">|</span> Kg</p>
                            <div className="flex justify-between w-full">
                                <p className="font-bold text-gray-600">Really Big Bananas</p>
                                <div className="flex justify-end w-full">
                                    <PlusIcon className="h-8 w-8 text-white bg-green-600 p-1 rounded-full"/>
                                </div>
                            </div>
                            {/* <p className="text-gray-600">6 miles away</p> */}
                        </div>
                        <div className="px-2">
                            <p className="font-bold">Reviews</p>
                            <div className="flex">
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-gray-400"/>
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col p-1 border rounded-2xl shadow-md space-y-2">
                        {/* header */}
                        <div className="py-2 flex justify-between items-center">
                            <p className="font-bold bg-green-600 text-white p-1 px-2 rounded-full">Fresh</p>
                            <ArrowCircleRightIcon className="h-8 w-8 text-gray-600"/>
                        </div>
                        <div className="relative h-32 w-full">
                            <Image src="/pineapples.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                        </div>
                        <div className="px-2">
                            <p className="font-bold">K10.99 <span className="text-gray-400">|</span> Kg</p>
                            <div className="flex justify-between w-full">
                                <p className="font-bold text-gray-600">Pineapples</p>
                                <div className="flex justify-end w-full">
                                    <PlusIcon className="h-8 w-8 text-white bg-green-600 p-1 rounded-full"/>
                                </div>
                            </div>
                            {/* <p className="text-gray-600">6 miles away</p> */}
                        </div>
                        <div className="px-2">
                            <p className="font-bold">Reviews</p>
                            <div className="flex">
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-gray-400"/>
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col p-1 border rounded-2xl shadow-md space-y-2">
                        {/* header */}
                        <div className="py-2 flex justify-between items-center">
                            <p className="font-bold bg-green-600 text-white p-1 px-2 rounded-full">Fresh</p>
                            <ArrowCircleRightIcon className="h-8 w-8 text-gray-600"/>
                        </div>
                        <div className="relative h-32 w-full">
                            <Image src="/strawberries.jpg" objectFit="cover" layout="fill" className="rounded-2xl"/>
                        </div>
                        <div className="px-2">
                            <p className="font-bold">K24.99 <span className="text-gray-400">|</span> Kg</p>
                            <div className="flex justify-between w-full">
                                <p className="font-bold text-gray-600">Strawberries</p>
                                <div className="flex justify-end w-full">
                                    <PlusIcon className="h-8 w-8 text-white bg-green-600 p-1 rounded-full"/>
                                </div>
                            </div>
                            {/* <p className="text-gray-600">6 miles away</p> */}
                        </div>
                        <div className="px-2">
                            <p className="font-bold">Reviews</p>
                            <div className="flex">
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-yellow-400"/>
                                <StarIcon className="h-5 w-5 text-gray-400"/>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <nav className="">
                <BottomNavBar />
            </nav> 
        </div>
    )
}

export default Store
