import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {useState, useEffect} from 'react'
import BottomNavBar from '../../components/BottonNavBar'
import Header from '../../components/Header'
import PuffLoader from "react-spinners/PuffLoader";
import { css } from "@emotion/react";
import { ArrowCircleLeftIcon, ArrowLeftIcon, BeakerIcon, BookmarkIcon, CloudIcon, EyeIcon, LocationMarkerIcon, ReceiptRefundIcon, RefreshIcon, SearchIcon, SunIcon, TrendingUpIcon } from '@heroicons/react/outline'
function Detailed() {
   
    // PuffLoader
    return (
        <div className="main">
            <Head>
                <title>Greenupp | Precision Weather</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="flex flex-col pt-24 h-screen px-4">
                <div className="flex justify-between w-full">
                    <div className="">
                        <ArrowLeftIcon className="h-6 w-6 text-gray-700"/>
                    </div>
                    <div className="">
                        <BookmarkIcon className="h-6 w-6 text-gray-700"/>
                    </div>
                </div>
                <div className="flex space-x-1 py-4">
                    <span className="text-3xl">Livingstone</span>
                    <span className="text-gray-500">Zambia</span>
                </div>
                <div className="flex overflow-auto mt-4 drop-shadow-md overflow-ellipsis">
                    <div className="text-sm p-4 font-bold">Sun</div>
                    <div className="text-sm bg-gray-200 p-4 rounded-full px-8 font-bold">Mon</div>
                    <div className="text-sm p-4 font-bold">Tue</div>
                    <div className="text-sm p-4 font-bold">Wed</div>
                    <div className="text-sm p-4 font-bold">Thu</div>
                    <div className="text-sm p-4 font-bold">Fri</div>
                    <div className="text-sm p-4 font-bold">Sat</div>
                </div>
                <div className="flex flex-col items-center justify-center h-60">
                    <CloudIcon className="h-32 w-32 text-gray-700"/>
                    <p className="text-6xl font-bold text-gray-500">24<sup>o</sup></p>
                </div>
                <div className="flex flex-col h-60 rounded-2xl w-full bg-gray-100 p-4 justify-between">
                    <div className="flex justify-around items-center">
                        <div className="flex items-center justify-center flex-col">
                            <ReceiptRefundIcon className="h-6 w-6 text-gray-500"/>
                            <p>621 hps</p>
                            <p className="text-gray-400">Pressure</p>
                        </div>
                        <div className="flex items-center justify-center flex-col">
                            <RefreshIcon className="h-6 w-6 text-gray-500"/>
                            <p>200 mph</p>
                            <p className="text-gray-400">Wind</p>
                        </div>
                        <div className="flex items-center justify-center flex-col">
                            <EyeIcon className="h-6 w-6 text-gray-500"/>
                            <p>44 m</p>
                            <p className="text-gray-400">VIsibility</p>
                        </div>
                    </div>
                    <div className="divider bg-gray-300 h-0.5"></div>
                    <div className="flex justify-around items-center">
                        <div className="flex items-center justify-center flex-col">
                            <BeakerIcon className="h-6 w-6 text-gray-500"/>
                            <p>75%</p>
                            <p className="text-gray-400">Humidity</p>
                        </div>
                        <div className="flex items-center justify-center flex-col">
                            <TrendingUpIcon className="h-6 w-6 text-gray-500"/>
                            <p>8 mph</p>
                            <p className="text-gray-400">Air Quality</p>
                        </div>
                        <div className="flex items-center justify-center flex-col">
                            <SunIcon className="h-6 w-6 text-gray-500"/>
                            <p>3</p>
                            <p className="text-gray-400">UV</p>
                        </div>
                    </div>
                </div>
            </section>
            <nav className="">
                <BottomNavBar />
            </nav> 
        </div>
    )
}

export default Detailed


