import React, {useState} from "react";
import Head from 'next/head'
import Image from 'next/image'
import BottomNavBar from '../../components/BottonNavBar'
import {useRouter} from 'next/router'
import Header from '../../components/Header'
import dynamic from 'next/dynamic'
import QrReader from 'react-qr-reader'

function Dashboard() {
    const [result, setResult] = useState('Scan')
    const handleScan = (result)=>{
        setResult(result)
    }       

    const handleError= (err) => {
        console.log(err)
    }

    const previewStyle = {
        height:600,
        width:500,
        display: 'flex',
        "justify-content": "center"
    }
    

    return (
        <div className="main">
            <Head>
                <title>Greenupp | Chat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className=" justify-center items-center h-screen">
                <>
                    <QrReader 
                        delay={300}
                        onError={this.handleError}
                        onScan={this.handleScan}
                        style={{ width: '100%' }}
                    />
                </>
                <p>{result}</p>
            </section>
            <nav className="">
                <BottomNavBar />
            </nav> 
        </div>
    )
}

export default Dashboard
