import React, {useState, useEffect} from "react";
import Head from 'next/head'
import Image from 'next/image'
import BottomNavBar from '../../components/BottonNavBar'
import {useRouter} from 'next/router'
import Header from '../../components/Header'
import dynamic from 'next/dynamic'
import axios from 'axios'
import { CameraIcon, ChevronDoubleRightIcon, ChevronRightIcon, FilterIcon, ShoppingCartIcon, ViewListIcon } from "@heroicons/react/outline";
import PuffLoader from "react-spinners/PuffLoader";
import { css } from "@emotion/react";


const QrReader = dynamic(() => import('react-qr-reader'), {
    ssr: false
})



function Qr() {
    const [result, setResult] = useState([])
    const router = useRouter()
    const [data, setData] = useState(false)
    let [color, setColor] = useState("#16a085");
    const [loading, setLoading] = useState(true)
    useEffect(() => {
        async function d(){
            // const res = await axios.get('http://localhost:3000/api/hello')
            // console.log(res)
            // const {productName,numDaysToExpire,pesticideInfo,packager,location,managerInfo,inspection,halaalCert, dateProcessed, batchNumber, freshNess, gmoStatus} = res.data
            // const array = [productName,numDaysToExpire,pesticideInfo,packager,location,managerInfo,inspection,halaalCert, dateProcessed, batchNumber, freshNess, gmoStatus]
            // array.push()
            // setResult(array)
            // console.log(result)
        }
        
    }, []);

    const handleScan = data => {
        if(data === null){
            setData(data);
        }
       if(data !== null) {
            setData(false);
            setLoading(true);
            router.replace(`/scan/results?data=${data}`)
       }
    }

    const handleError = (err) => {
        alert("Please allow carema permissions and reload page.")
        console.error(err)
    }

    const override = css`
        display: block;
        margin: 0 auto;
        border-color: #16a085;
        `;

    return (
        <div className="main">
            <Head>
                <title>Greenupp | Scan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="h-screen pt-16 rounded-2xl">
                
                <div className="">
                    <QrReader
                        className=""
                        delay={300}
                        onError={handleError}
                        onScan={handleScan}
                        style={{ width: "100%", backgroundColor: "black"}}
                    />
                </div>
                <div className="flex items-center flex-col justify-center py-5 px-4 space-y-3">
                    {
                        data=== null? <p>Place your camera in front of the QR Code. 🙄</p>: null
                    }
                    <PuffLoader color={color} loading={loading} css={override} size={60} />
                    
                    <button onClick={() =>{
                        router.push('/scan')
                    }}  className="rounded-full shadow-md bg-green-600 w-1/2 p-4 text-white font-bold uppercase">Cancel Scan</button>
                </div>
            </section>
            
            
        </div>
    )
}

export default Qr
